name: Manual trigger 2
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Who to greet"
        default: "DR"
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
        - name: Hello Step
          run: echo "Hello ${{ github.event.inputs.name }}"
