name: Label PRs based on source branch dr

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Label PR based on source branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SPECIFIC_BRANCH="master"
          if [ "${{ github.event.pull_request.head.ref }}" != "$SPECIFIC_BRANCH" ]; then
            gh pr edit ${{ github.event.pull_request.number }} --add-label "auto-approved"
            gh pr comment ${{ github.event.pull_request.number }} --body "Cette PR n'est pas de la branche $SPECIFIC_BRANCH et peut être fusionnée sans revue manuelle."
          else
            gh pr edit ${{ github.event.pull_request.number }} --add-label "needs-review"
            gh pr comment ${{ github.event.pull_request.number }} --body "Cette PR provient de $SPECIFIC_BRANCH et nécessite une revue manuelle."
          fi
